PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Registrations;
CREATE TABLE Registrations (
    UserId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Username VARCHAR(30) NOT NULL UNIQUE,
    UserPassword VARCHAR(30) NOT NULL,
    BearerToken VARCHAR(255)
);
DROP TABLE IF EXISTS Roles;
CREATE TABLE Roles (
    RoleId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    RoleName VARCHAR(30) NOT NULL
);
INSERT INTO Roles VALUES 
(1, 'Student'),
(2, 'Instructor'),
(3, 'Registrar');
DROP TABLE IF EXISTS UserRoles;
CREATE TABLE UserRoles (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    RoleId INT NOT NULL REFERENCES Roles(RoleId),
    UserId INT NOT NULL REFERENCES Registrations(UserId)
);
COMMIT;
